const express = require('express')
const controller = require('../controllers/message.controller.js')
const keyVerify = require('../middlewares/keyCheck')
const loginVerify = require('../middlewares/loginCheck')
const multer = require('multer')

const router = express.Router()
const storage = multer.memoryStorage()
const upload = multer({ storage: storage, inMemory: true }).single('file')

router.route('/text').post(keyVerify, loginVerify, controller.text)
router.route('/image').post(keyVerify, loginVerify, upload, controller.image)
router.route('/video').post(keyVerify, loginVerify, upload, controller.video)
router.route('/audio').post(keyVerify, loginVerify, upload, controller.audio)
router.route('/doc').post(keyVerify, loginVerify, upload, controller.document)
router.route('/media-url').post(keyVerify, loginVerify, controller.mediaUrl)
router.route('/button').post(keyVerify, loginVerify, controller.button)
router.route('/contact').post(keyVerify, loginVerify, controller.contact)
router.route('/list').post(keyVerify, loginVerify, controller.list)
router.route('/set-status').put(keyVerify, loginVerify, controller.setStatus)
router.route('/media-button').post(keyVerify, loginVerify, controller.mediaButton)
router.route("/read").post(keyVerify, loginVerify, controller.read)
router.route("/react").post(keyVerify, loginVerify, controller.react)

module.exports = router
